// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsUKHjARKPUIG_uPIvbTrcr9h7JvCUtlw',
    appId: '1:783228038188:web:ccf4c6445e70abfbcc7589',
    messagingSenderId: '783228038188',
    projectId: 'agenda-ptval',
    authDomain: 'agenda-ptval.firebaseapp.com',
    storageBucket: 'agenda-ptval.appspot.com',
    measurementId: 'G-QZZ6XY2GMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAku9wPfyrwfRK26Ft3hL2kHPwiaYN__8',
    appId: '1:783228038188:android:70d9532b146b1d0ecc7589',
    messagingSenderId: '783228038188',
    projectId: 'agenda-ptval',
    storageBucket: 'agenda-ptval.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsJdNj6SgqG1VoJr_jGc1D87NzphHLjkg',
    appId: '1:783228038188:ios:3d6d839e2630ba61cc7589',
    messagingSenderId: '783228038188',
    projectId: 'agenda-ptval',
    storageBucket: 'agenda-ptval.appspot.com',
    iosBundleId: 'com.example.agendaPtval',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsJdNj6SgqG1VoJr_jGc1D87NzphHLjkg',
    appId: '1:783228038188:ios:3d6d839e2630ba61cc7589',
    messagingSenderId: '783228038188',
    projectId: 'agenda-ptval',
    storageBucket: 'agenda-ptval.appspot.com',
    iosBundleId: 'com.example.agendaPtval',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsUKHjARKPUIG_uPIvbTrcr9h7JvCUtlw',
    appId: '1:783228038188:web:38521ebd08e6b795cc7589',
    messagingSenderId: '783228038188',
    projectId: 'agenda-ptval',
    authDomain: 'agenda-ptval.firebaseapp.com',
    storageBucket: 'agenda-ptval.appspot.com',
    measurementId: 'G-ZLHPSDVN34',
  );
}
